"use client";

import { useMemo, useState } from "react";
import { calculateTrade, formatCurrency, formatPercent, type Trade, type TradeMetric } from "@/lib/trades";

type Props = { trades: Trade[]; rows: TradeMetric[]; onUpdate: (id: string, patch: Partial<Trade>) => void };

export function ProJournalInsights({ trades, rows, onUpdate }: Props) {
  const [selectedId, setSelectedId] = useState(trades[0]?.id ?? "");
  const [reviewFilter, setReviewFilter] = useState<"all" | "wins" | "losses" | "open" | "review">("all");
  const closed = rows.filter((r) => r.positionStatus === "Closed");
  const wins = closed.filter((r) => r.grossPL > 0);
  const losses = closed.filter((r) => r.grossPL < 0);
  const expectancy = closed.length ? closed.reduce((sum, r) => sum + r.grossPL, 0) / closed.length : 0;
  const avgWin = wins.length ? wins.reduce((sum, r) => sum + r.grossPL, 0) / wins.length : 0;
  const avgLoss = losses.length ? losses.reduce((sum, r) => sum + r.grossPL, 0) / losses.length : 0;
  const filtered = useMemo(() => rows.filter((r) => reviewFilter === "all" || (reviewFilter === "wins" && r.grossPL > 0) || (reviewFilter === "losses" && r.grossPL < 0) || (reviewFilter === "open" && r.positionStatus !== "Closed") || (reviewFilter === "review" && !r.quickNote)), [reviewFilter, rows]);
  const trade = trades.find((t) => t.id === selectedId) ?? trades[0];
  const selected = trade ? calculateTrade(trade) : null;
  const setupStats = Object.entries(rows.reduce<Record<string, { pl: number; count: number }>>((acc, r) => { const key = r.setup || "No setup"; acc[key] ??= { pl: 0, count: 0 }; acc[key].pl += r.grossPL; acc[key].count++; return acc; }, {})).sort((a, b) => b[1].pl - a[1].pl).slice(0, 4);

  return <section className="flex flex-col gap-3" aria-label="Professional trading review">
    <div className="grid gap-3 lg:grid-cols-[1.25fr_1fr]">
      <div className="rounded-2xl border border-[#e5e9e6] bg-[#17251d] p-4 text-white shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#9db3a5]">Trading review</p><h2 className="mt-1 text-xl font-bold tracking-tight">Trade with a process, not a feeling.</h2></div><span className="rounded-full bg-[#2a4938] px-2 py-1 text-[10px] text-[#b7d7c1]">{closed.length} closed</span></div><div className="mt-5 grid grid-cols-3 gap-2"><div><p className="text-[10px] text-[#9db3a5]">Expectancy</p><p className={`mt-1 text-lg font-bold ${expectancy >= 0 ? "text-[#74d49b]" : "text-[#ff9dad]"}`}>{formatCurrency(expectancy, 0)}</p></div><div><p className="text-[10px] text-[#9db3a5]">Avg win</p><p className="mt-1 text-lg font-bold text-[#74d49b]">{formatCurrency(avgWin, 0)}</p></div><div><p className="text-[10px] text-[#9db3a5]">Avg loss</p><p className="mt-1 text-lg font-bold text-[#ff9dad]">{formatCurrency(avgLoss, 0)}</p></div></div></div>
      <div className="rounded-2xl border border-[#e5e9e6] bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[#89918c]">Setup scorecard</p><p className="mt-1 text-sm font-bold text-[#253129]">Where your edge is showing</p></div><p className="text-xs font-bold text-[#15955f]">{formatPercent(closed.length ? wins.length / closed.length * 100 : 0)}</p></div><div className="mt-4 flex flex-col gap-2">{setupStats.length ? setupStats.map(([name, stat]) => <div key={name} className="flex items-center justify-between text-xs"><span className="truncate text-[#606a64]">{name}</span><span className={stat.pl >= 0 ? "font-bold text-[#15955f]" : "font-bold text-[#e14f69]"}>{formatCurrency(stat.pl, 0)} <span className="font-normal text-[#a0a7a3]">· {stat.count}</span></span></div>) : <p className="text-xs text-[#89918c]">Add trades to build your scorecard.</p>}</div></div>
    </div>
    <div className="grid gap-3 lg:grid-cols-[1fr_1.25fr]">
      <div className="rounded-2xl border border-[#e5e9e6] bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[#89918c]">Review queue</p><p className="mt-1 text-sm font-bold text-[#253129]">Find the next lesson</p></div><span className="text-xs text-[#89918c]">{filtered.length} trades</span></div><div className="mt-3 flex flex-wrap gap-1.5">{(["all", "wins", "losses", "open", "review"] as const).map((filter) => <button key={filter} type="button" onClick={() => setReviewFilter(filter)} className={`rounded-full px-2.5 py-1 text-[10px] font-semibold capitalize ${reviewFilter === filter ? "bg-[#17251d] text-white" : "bg-[#f2f5f3] text-[#65716a]"}`}>{filter}</button>)}</div><div className="mt-3 flex max-h-40 flex-col gap-1 overflow-auto">{filtered.slice(0, 12).map((row) => <button key={row.id} type="button" onClick={() => setSelectedId(row.id)} className={`flex items-center justify-between rounded-lg px-2 py-1.5 text-left text-xs ${selectedId === row.id ? "bg-[#edf7f1]" : "hover:bg-[#f7f9f8]"}`}><span className="font-semibold text-[#425047]">{row.name || "Unnamed"}</span><span className={row.grossPL >= 0 ? "text-[#15955f]" : "text-[#e14f69]"}>{row.positionStatus === "Closed" ? formatCurrency(row.grossPL, 0) : "Open"}</span></button>)}</div></div>
      <div className="rounded-2xl border border-[#e5e9e6] bg-white p-4 shadow-sm"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[#89918c]">Trade review</p><p className="mt-1 text-sm font-bold text-[#253129]">{trade?.name || "Select a trade"} {selected ? <span className="font-normal text-[#89918c]">· {selected.positionStatus}</span> : null}</p></div>{trade && <select aria-label="Select trade" value={selectedId} onChange={(e) => setSelectedId(e.target.value)} className="max-w-32 rounded-lg border border-[#dfe6e1] px-2 py-1 text-xs"><option value={trade.id}>{trade.name}</option>{trades.filter((t) => t.id !== trade.id).slice(0, 20).map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</select>}</div>{trade ? <div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-[10px] font-semibold uppercase tracking-wider text-[#89918c]">Plan followed<select aria-label="Plan followed" value={trade.planFollowed} onChange={(e) => onUpdate(trade.id, { planFollowed: e.target.value })} className="mt-1 w-full rounded-lg border border-[#dfe6e1] bg-white px-2 py-2 text-xs"><option value="">Not reviewed</option><option>Yes</option><option>No</option><option>Partial</option></select></label><label className="text-[10px] font-semibold uppercase tracking-wider text-[#89918c]">Exit trigger<input aria-label="Exit trigger" value={trade.exitTrigger} onChange={(e) => onUpdate(trade.id, { exitTrigger: e.target.value })} className="mt-1 w-full rounded-lg border border-[#dfe6e1] px-2 py-2 text-xs" placeholder="Why did you exit?" /></label><label className="text-[10px] font-semibold uppercase tracking-wider text-[#89918c] sm:col-span-2">Quick note<textarea aria-label="Quick note" value={trade.quickNote} onChange={(e) => onUpdate(trade.id, { quickNote: e.target.value })} className="mt-1 min-h-16 w-full resize-y rounded-lg border border-[#dfe6e1] px-2 py-2 text-xs" placeholder="What worked, what failed, what will you repeat?" /></label></div> : <p className="mt-4 text-xs text-[#89918c]">Add a trade to start reviewing.</p>}</div>
    </div>
  </section>;
}

export default ProJournalInsights;
